version: "3.8"

networks:
   images_storage_network:
      name: "images_storage_network"

services:
   images_storage_service:
      build: ./
      command: ./bin/app
      # ports:
      #    - 8080
      networks:
         - images_storage_network
         - tracing_network
      volumes:
         - ./docker/containers-configs/app-configs/:/configs
         - ./.container_data/images/:/images/
      environment:
         BASE_LOCAL_STORAGE_PATH: images/
      healthcheck:
         test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
         interval: 40s
         timeout: 10s
         retries: 2
         start_period: 20s
      deploy:
         mode: replicated
         replicas: 3
         endpoint_mode: dnsrr
         restart_policy:
          condition: unless-stopped
      labels:
         servicename: "images_storage_service"
         org.label-schema.group: "monitoring"
