version: '3.8'

networks:
  tracing_network:
    name: "tracing_network"


services:
  prometheus:
      container_name: prometheus_container
      image: prom/prometheus
      hostname: prometheus
      volumes:
        - ./docker/containers-configs/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=20d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      networks:
        - tracing_network
        
  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    hostname: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - tracing_network

  node_exporter:
    container_name: node_exporter_container
    image: prom/node-exporter
    ports:
      - 9101:9100
    networks:
     - tracing_network

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
     - tracing_network
