version: '3.8'

networks:
  tracing_network:
    name: "tracing_network"


services:
  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    hostname: prometheus
    volumes:
      - ./docker/containers-configs/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.container_data/prometheus/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - tracing_network
    depends_on:
      - node_exporter
    labels:
      org.label-schema.group: "monitoring"

  jaeger:
    container_name: jaeger_container
    image: jaegertracing/all-in-one:1.21
    hostname: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - tracing_network

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100
    networks:
      - tracing_network
    # network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    restart: unless-stopped
    environment:
    - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - ./grafana/data:/var/lib/grafana/
    ports:
      - 3000:3000
    networks:
     - tracing_network