version: '3.8'

include:
  - accounts_db/accounts_db.yml
  - accounts_service/accounts_service.yml
  - profiles_service/profiles_service.yml
  - tracing_service/tracing_service.yml
  - email_service/email_service.yml
  - kafka-cluster/kafka-cluster.yml
  - images_storage_service/images_storage_service.yml


services:
    gateway:
      image: nginx 
      ports:
        - 80:80
        - 81:81
      networks:
        - profiles_service_network
        - accounts_service_network
        - images_storage_network
      volumes:
        - .nginx/configs/nginx.conf:/etc/nginx/nginx.conf
        - .nginx/configs/services.conf:/etc/nginx/services.conf
        - .nginx/configs/rules.conf:/etc/nginx/rules.conf
      depends_on:
        - accounts_service
        - profiles_service
        - email_service
        - images_storage_service
        - prometheus
        - jaeger
        - node_exporter
        - grafana



        