version: '3.8'

include:
  - accounts_db/accounts_db.yml
  - accounts_service/accounts_service.yml
  - profiles_service/profiles_service.yml
  - tracing_service/tracing_service.yml
  - email_service/email_service.yml
  - kafka-cluster/kafka-cluster.yml
  - image_storage_service/image_storage_service.yml


services:
    gateway:
      image: nginx 
      ports:
        - 80:80
      networks:
        - profiles_service_network
       # - accounts_service_network
        - tracing_network
      volumes:
        - .nginx/configs/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - accounts_service
        - profiles_service
        - email_service
        - image_storage_service
        - prometheus
        - jaeger
        - node_exporter
        - grafana



        