---

mode: "debug" #debug test release
jwt:
  tokenTTL: 30 #in minutes
  refresh_tokenTTL: 180 #in minutes
  verify_account_tokenTTL: 180 #in minutes
listen:
  type: port
  bind_ip: 127.0.0.1
  port: "8080"
  domain: "localhost"
contexts:
  user_context: "user_context"
account_service:
  url: localhost:7070
user_service:
  url: localhost:10000
image_storage_service:
  url: localhost:7012
movie_posters_service:
  url: http:/ns-movie_posters_service:10001/api
