version: "3.8"

networks:
  minio_storage_network:
    name: "minio_storage_network"

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-12-23T07-19-11Z
  command: server --console-address ":9001" /data
  expose:
    - 9000
    - 9001
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  networks:
    - minio_storage_network
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 5s
    timeout: 5s
    retries: 5
  deploy:
      restart_policy:
        condition: unless-stopped
services:
  minio1:
    <<: *minio-common
    volumes:
      - ./.container_data:/data

  minio_gateway:
    image: nginx
    container_name: minio_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio_storage_network
    depends_on:
      - minio1
    deploy:
      restart_policy:
        condition: unless-stopped