version: "3.8"

include:
  - ../../databases//movies_persons_db/movies_persons_db.yml

networks:
  movies_persons_service_network:
    name: "movies_persons_service_net"
    driver: bridge

services:
  movies_persons_service:
    hostname: movies_persons_service
    image: falokut/movies_persons_service
    volumes:
      - ./docker/containers-configs/:/configs
    # ports:
    #   - 9902:8080
    networks:
      - movies_persons_service_network
      - movies_persons_db_network
      - gateway_network
      - tracing_network
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      MOVIES_PERSONS_CACHE_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      movies_persons_db:
        condition: service_healthy
      movies_persons_cache:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "movies_persons_service"
      org.label-schema.group: "monitoring"

  movies_persons_cache:
    hostname: redis
    image: redis:7.2.1-alpine
    volumes:
      - ./.container_data/cache/data:/data
    # ports:
    #   - 6376:6379
    networks:
      - movies_persons_service_network
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_AOF_ENABLED: ${REDIS_AOF_ENABLED}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: unless-stopped