global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'accounts_service'
    static_configs:
      - targets: ['accounts_service:7000']

  - job_name: 'profiles_service'
    static_configs:
      - targets: ['profiles_service:7000']