version: "3.8"

include:
  - ../../databases/cinema_db/cinema_db.yml
networks:
  admin_cinema_service_network:
    name: "admin_cinema_service_net"
    driver: bridge

services:
  admin_cinema_service:
    image: falokut/admin_cinema_service
    volumes:
      - ./docker/containers-configs/:/configs
    expose:
      - 8080
    networks:
      - admin_cinema_service_network
      - cinema_db_network
      - tracing_network
      - admin_gateway_network
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      cinema_pool:
        condition: service_started
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "admin_admin_cinema_service"
      org.label-schema.group: "monitoring"
