version: '3.8'


include:
- ../accounts_db/accounts_db.yml
- ../kafka-cluster/kafka-cluster.yml
networks:
  accounts_service_network:
    name: "accounts_service_net"
    driver: bridge

services:
  accounts_service:
   hostname: accounts_service
   build: ./
   command: ./bin/app
   volumes:
     - ./docker/containers-configs/app-configs/:/configs
  #  ports:
  #     - 8000:8080
   networks:
     - accounts_service_network
     - kafka_network
     - accounts_db_network
     - tracing_network 
   depends_on:
      redis:
        condition: service_healthy
      accounts_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
   deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
   labels:
      servicename: "accounts_service"
      org.label-schema.group: "monitoring"

  redis:
    container_name: account_service_cache
    hostname: redis
    image: redis:7.2.1-alpine
    volumes:
      - ./.container_data/cache/data:/data
    ports:
      - 6378:6379
    networks:
      - accounts_service_network
    env_file:
      - docker/containers-configs/redis.env
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s