version: "3.8"

networks:
   image_storage_network:
      name: "image_storage_network"
      
services:
  image_storage_service:
   hostname: image_storage_service
   build: ./
   command: ./bin/app
   ports:
      - 8010:8080
   networks:
      - image_storage_network
      - tracing_network 
   volumes:
      - ./docker/containers-configs/app-configs/:/configs
      - ./.container_data/images/:/images/
   environment:
      - BASE_LOCAL_STORAGE_PATH=images/
   deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s