version: "3.8"

include:
  - ../../databases/genres_db/genres_db.yml

networks:
  genres_service_network:
    name: "genres_service_net"
    driver: bridge

services:
  genres_service:
    hostname: genres_service
    image: falokut/genres_service
    volumes:
      - ./docker/containers-configs/:/configs
    # ports:
    #   - 9902:8080
    networks:
      - genres_service_network
      - genres_db_network
      - gateway_network
      - tracing_network
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      GENRES_CACHE_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      genres_db:
        condition: service_healthy
      genres_service_cache:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "genres_service"
      org.label-schema.group: "monitoring"

  genres_service_cache:
    hostname: redis
    image: redis:7.2.1-alpine
    volumes:
      - ./.container_data/cache/data:/data
    # ports:
    #   - 6376:6379
    networks:
      - genres_service_network
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_AOF_ENABLED: ${REDIS_AOF_ENABLED}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: unless-stopped