version: "3.8"

include:
  - ../../databases/profiles_db/profiles_db.yml

networks:
  profiles_service_network:
    name: "profiles_service_network"
    driver: bridge

services:
  profiles_service:
    hostname: profiles_service
    image: falokut/profiles_service-alpine:latest
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/containers-configs/config.yml:/configs/config.yml
    expose:
      - 8080
    networks:
      - profiles_service_network
      - profiles_db_network
      - tracing_network
      - gateway_network
      - kafka_network
    depends_on:
      profiles_pool:
        condition: service_started
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "profiles_service"
      org.label-schema.group: "monitoring"
