version: '3.8'

networks:
  admin_image_processing_service_network:
    name: "admin_image_processing_service_network"

services:
  admin_image_processing_service:
    image: falokut/image_processing_service
    environment:
      ENABLE_METRICS: true
    # ports:
    #  - 8080
    networks:
     - admin_image_processing_service_network
     - tracing_network
     - admin_gateway_network
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
          condition: unless-stopped
    volumes:
     - ./docker/containers-configs/:/configs
    labels:
      servicename: "admin_image_processing_service"
      org.label-schema.group: "monitoring"
