log_level: "warning" # supported levels: "panic", "fatal", "error", "warning" or "warn", "info", "debug", "trace"

listen:
  type: port
  bind_ip: 127.0.0.1
  port: 10000
dbconfig: 
  host: "localhost"
  port: "5432"
  username: "postgres"
  db_name: "cinema_office_users_db"
  ssl_mode: "disable"

