version: "3.8"

include:
  - ../../databases/accounts_db/accounts_db.yml
  - ../kafka-cluster/kafka-cluster.yml

networks:
  accounts_service_network:
    name: "accounts_service_net"
    driver: bridge

services:
  accounts_service:
    image: falokut/accounts_service
    volumes:
      - ./docker/containers-configs:/configs
    #  ports:
    #    - 8080
    networks:
      - accounts_service_network
      - kafka_network
      - accounts_db_network
      - tracing_network
      - gateway_network
    depends_on:
      redis:
        condition: service_healthy
      accounts_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "accounts_service"
      org.label-schema.group: "monitoring"

  redis:
    container_name: account_service_cache
    hostname: redis
    image: redis:7.2.1-alpine
    volumes:
      - ./.container_data/cache/data:/data
    ports:
      - 6378:6379
    networks:
      - accounts_service_network
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_AOF_ENABLED}
      REDIS_AOF_ENABLED: ${REDIS_AOF_ENABLED}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: unless-stopped
