log_level: "debug" # supported levels: "panic", "fatal", "error", "warning" or "warn", "info", "debug", "trace"

listen:
  host: 0.0.0.0
  port: 8080
  server_mode: "BOTH"

jaeger:
  service_name: "Images_Processing_Service"
  address: jaeger:6831
  log_spans: true

prometheus:
  service_name: "Images_Processing_Service"
  server_config:
    host: 0.0.0.0
    port: 7000