global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:9102']

  - job_name: profiles_service
    dns_sd_configs:
    - names:
        - profiles_service
      type: A
      port: 7000

  - job_name: accounts_service
    dns_sd_configs:
      - names:
          - accounts_service
        type: A
        port: 7000
        
  - job_name: images_storage_service
    dns_sd_configs:
      - names:
          - images_storage_service
        type: A
        port: 7000

  - job_name: images_processing_service
    dns_sd_configs:
      - names:
          - images_processing_service
        type: A
        port: 7000