version: '3.8'

networks:
  kafka_network:
    name: "kafka_network"
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka_network
    deploy:
      restart_policy:
          condition: unless-stopped
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s 

  kafka:
    image: wurstmeister/kafka
    ports:
      - 29092:29092
    networks:
      - kafka_network
    volumes:
      - ./.container_data/kafka/:/kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "emails:2:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
          condition: unless-stopped

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    volumes:
      - ./.container_data/kafka-ui/:/etc/kafkaui
    ports:
      - 18082:8080
    networks:
      - kafka_network
    environment:
      DYNAMIC_CONFIG_ENABLED: true

