log_level: "debug" # supported levels: "panic", "fatal", "error", "warning" or "warn", "info", "debug", "trace"
healthcheck_port: 7001

listen:
  host: 0.0.0.0
  port: 8080
  server_mode: "BOTH"
  
db_config: 
  host: "casts_pool"
  port: "6432"
  username: "admin_casts_service"
  db_name: "casts"
  ssl_mode: "disable"
  
jaeger:
  service_name: "Admin_Casts_Service"
  address: jaeger:6831
  log_spans: true

prometheus:
  service_name: "Admin_Casts_Service"
  server_config:
    host: 0.0.0.0
    port: 7000


movies_events_kafka:
  brokers:
    - "kafka:9092"
  group_id: "casts_service"
  read_batch_timeout: 30s

persons_events_kafka:
  brokers:
    - "kafka:9092"
  group_id: "casts_service"
  read_batch_timeout: 30s

movies_service:
  addr: admin_gateway:81
movies_persons_service:
  addr: admin_gateway:81



