version: "3.8"

include:
  - ../kafka-cluster/kafka-cluster.yml

services:
  email_service:
    build: ./
    command: ./bin/app
    networks:
      - kafka_network
    volumes:
      - ./docker/containers-configs/app-configs/config.yml:/configs/config.yml
    depends_on:
      - kafka
    env_file:
      - ./docker/containers-configs/app-configs/.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
