// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: images_storage_service_v1.proto

package protos

import (
	context "context"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImagesStorageServiceV1Client is the client API for ImagesStorageServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImagesStorageServiceV1Client interface {
	UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponce, error)
	StreamingUploadImage(ctx context.Context, opts ...grpc.CallOption) (ImagesStorageServiceV1_StreamingUploadImageClient, error)
	GetImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
	IsImageExist(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageExistResponce, error)
	DeleteImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReplaceImage(ctx context.Context, in *ReplaceImageRequest, opts ...grpc.CallOption) (*ReplaceImageResponce, error)
}

type imagesStorageServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewImagesStorageServiceV1Client(cc grpc.ClientConnInterface) ImagesStorageServiceV1Client {
	return &imagesStorageServiceV1Client{cc}
}

func (c *imagesStorageServiceV1Client) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponce, error) {
	out := new(UploadImageResponce)
	err := c.cc.Invoke(ctx, "/images_storage_service.ImagesStorageServiceV1/UploadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesStorageServiceV1Client) StreamingUploadImage(ctx context.Context, opts ...grpc.CallOption) (ImagesStorageServiceV1_StreamingUploadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImagesStorageServiceV1_ServiceDesc.Streams[0], "/images_storage_service.ImagesStorageServiceV1/StreamingUploadImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imagesStorageServiceV1StreamingUploadImageClient{stream}
	return x, nil
}

type ImagesStorageServiceV1_StreamingUploadImageClient interface {
	Send(*StreamingUploadImageRequest) error
	CloseAndRecv() (*UploadImageResponce, error)
	grpc.ClientStream
}

type imagesStorageServiceV1StreamingUploadImageClient struct {
	grpc.ClientStream
}

func (x *imagesStorageServiceV1StreamingUploadImageClient) Send(m *StreamingUploadImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imagesStorageServiceV1StreamingUploadImageClient) CloseAndRecv() (*UploadImageResponce, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadImageResponce)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imagesStorageServiceV1Client) GetImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, "/images_storage_service.ImagesStorageServiceV1/GetImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesStorageServiceV1Client) IsImageExist(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageExistResponce, error) {
	out := new(ImageExistResponce)
	err := c.cc.Invoke(ctx, "/images_storage_service.ImagesStorageServiceV1/IsImageExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesStorageServiceV1Client) DeleteImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/images_storage_service.ImagesStorageServiceV1/DeleteImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesStorageServiceV1Client) ReplaceImage(ctx context.Context, in *ReplaceImageRequest, opts ...grpc.CallOption) (*ReplaceImageResponce, error) {
	out := new(ReplaceImageResponce)
	err := c.cc.Invoke(ctx, "/images_storage_service.ImagesStorageServiceV1/ReplaceImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImagesStorageServiceV1Server is the server API for ImagesStorageServiceV1 service.
// All implementations must embed UnimplementedImagesStorageServiceV1Server
// for forward compatibility
type ImagesStorageServiceV1Server interface {
	UploadImage(context.Context, *UploadImageRequest) (*UploadImageResponce, error)
	StreamingUploadImage(ImagesStorageServiceV1_StreamingUploadImageServer) error
	GetImage(context.Context, *ImageRequest) (*httpbody.HttpBody, error)
	IsImageExist(context.Context, *ImageRequest) (*ImageExistResponce, error)
	DeleteImage(context.Context, *ImageRequest) (*emptypb.Empty, error)
	ReplaceImage(context.Context, *ReplaceImageRequest) (*ReplaceImageResponce, error)
	mustEmbedUnimplementedImagesStorageServiceV1Server()
}

// UnimplementedImagesStorageServiceV1Server must be embedded to have forward compatible implementations.
type UnimplementedImagesStorageServiceV1Server struct {
}

func (UnimplementedImagesStorageServiceV1Server) UploadImage(context.Context, *UploadImageRequest) (*UploadImageResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedImagesStorageServiceV1Server) StreamingUploadImage(ImagesStorageServiceV1_StreamingUploadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamingUploadImage not implemented")
}
func (UnimplementedImagesStorageServiceV1Server) GetImage(context.Context, *ImageRequest) (*httpbody.HttpBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedImagesStorageServiceV1Server) IsImageExist(context.Context, *ImageRequest) (*ImageExistResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsImageExist not implemented")
}
func (UnimplementedImagesStorageServiceV1Server) DeleteImage(context.Context, *ImageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedImagesStorageServiceV1Server) ReplaceImage(context.Context, *ReplaceImageRequest) (*ReplaceImageResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceImage not implemented")
}
func (UnimplementedImagesStorageServiceV1Server) mustEmbedUnimplementedImagesStorageServiceV1Server() {
}

// UnsafeImagesStorageServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagesStorageServiceV1Server will
// result in compilation errors.
type UnsafeImagesStorageServiceV1Server interface {
	mustEmbedUnimplementedImagesStorageServiceV1Server()
}

func RegisterImagesStorageServiceV1Server(s grpc.ServiceRegistrar, srv ImagesStorageServiceV1Server) {
	s.RegisterService(&ImagesStorageServiceV1_ServiceDesc, srv)
}

func _ImagesStorageServiceV1_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesStorageServiceV1Server).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images_storage_service.ImagesStorageServiceV1/UploadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesStorageServiceV1Server).UploadImage(ctx, req.(*UploadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImagesStorageServiceV1_StreamingUploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImagesStorageServiceV1Server).StreamingUploadImage(&imagesStorageServiceV1StreamingUploadImageServer{stream})
}

type ImagesStorageServiceV1_StreamingUploadImageServer interface {
	SendAndClose(*UploadImageResponce) error
	Recv() (*StreamingUploadImageRequest, error)
	grpc.ServerStream
}

type imagesStorageServiceV1StreamingUploadImageServer struct {
	grpc.ServerStream
}

func (x *imagesStorageServiceV1StreamingUploadImageServer) SendAndClose(m *UploadImageResponce) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imagesStorageServiceV1StreamingUploadImageServer) Recv() (*StreamingUploadImageRequest, error) {
	m := new(StreamingUploadImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ImagesStorageServiceV1_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesStorageServiceV1Server).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images_storage_service.ImagesStorageServiceV1/GetImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesStorageServiceV1Server).GetImage(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImagesStorageServiceV1_IsImageExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesStorageServiceV1Server).IsImageExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images_storage_service.ImagesStorageServiceV1/IsImageExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesStorageServiceV1Server).IsImageExist(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImagesStorageServiceV1_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesStorageServiceV1Server).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images_storage_service.ImagesStorageServiceV1/DeleteImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesStorageServiceV1Server).DeleteImage(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImagesStorageServiceV1_ReplaceImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesStorageServiceV1Server).ReplaceImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images_storage_service.ImagesStorageServiceV1/ReplaceImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesStorageServiceV1Server).ReplaceImage(ctx, req.(*ReplaceImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImagesStorageServiceV1_ServiceDesc is the grpc.ServiceDesc for ImagesStorageServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImagesStorageServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "images_storage_service.ImagesStorageServiceV1",
	HandlerType: (*ImagesStorageServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadImage",
			Handler:    _ImagesStorageServiceV1_UploadImage_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _ImagesStorageServiceV1_GetImage_Handler,
		},
		{
			MethodName: "IsImageExist",
			Handler:    _ImagesStorageServiceV1_IsImageExist_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImagesStorageServiceV1_DeleteImage_Handler,
		},
		{
			MethodName: "ReplaceImage",
			Handler:    _ImagesStorageServiceV1_ReplaceImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingUploadImage",
			Handler:       _ImagesStorageServiceV1_StreamingUploadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "images_storage_service_v1.proto",
}
