version: "3.8"

networks:
  cinema_orders_service_network:
    name: "cinema_orders_service_net"
    driver: bridge

services:
  cinema_orders_service:
    image: falokut/cinema_orders_service-alpine:latest
    volumes:
      - ./docker/containers-configs/:/configs
    expose:
      - 8080
    networks:
      - cinema_orders_service_network
      - gateway_network
      - kafka_network
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      RESERVE_CACHE_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      cinema_orders_service_cache:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "cinema_orders_service"
      org.label-schema.group: "monitoring"

  cinema_orders_service_cache:
    image: redis:7.2.1-alpine
    volumes:
      - ./.container_data/cache/data:/data
    expose:
      - 6379
    networks:
      - cinema_orders_service_network
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_AOF_ENABLED: ${REDIS_AOF_ENABLED}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: unless-stopped
