version: '3.8'

include:
- ../accounts_db/accounts_db.yml
- ../images_storage_service/images_storage_service.yml

networks:
  profiles_service_network:
    name: "profiles_service_network"
    driver: bridge

services:
  profiles_service:
   hostname: profiles_service
   build: ./
   command: ./bin/app
   volumes:
   - ./docker/containers-configs/app-configs/:/configs
  # ports:
      #- 8005:8080
   networks:
     - profiles_service_network
     - accounts_db_network
     - tracing_network
     - images_storage_network
   depends_on:
     - accounts_db
     - images_storage_service
   deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
          condition: unless-stopped
   labels:
     servicename: "profiles_service"
     org.label-schema.group: "monitoring"
